local M = {}

M.diagnostics = {
    default     = '#10c981',
    error       = '#e55561',
    warning     = '#e2b86b',
    information = '#48b0bd',
    hint        = '#bf68d9',
}

M.indents = {
    '#ff8888',
    '#88ffff',
    '#88ff88',
    '#ff88ff',
    '#8888ff',
    '#ffff88',
    backgrounds = {
        '#1a1a1a',
        '#1f1f1f',
    },
    context = '#8a2be2',
}

M.treesitter = {
    Attribute          = { fg = '#2efb57', italic = true },
    Boolean            = '#9370db',
    Character          = '#00fa9a',
    CharacterSpecial   = '#ff6347',
    Comment            = { fg = '#535965', italic = true },
    Conditional        = '#bf68d9',
    Constant           = { fg = '#daa520', bold = true },
    ConstBuiltin       = { fg = '#dac520', bold = true },
    ConstMacro         = { fg = '#daa540', bold = true },
    Constructor        = { fg = '#ff4400', bold = true },
    Debug              = '#e2b86b',
    Define             = { fg = '#bf68f9', bold = true },
    Error              = '#e55561',
    Exception          = '#bf68d9',
    Field              = '#48b0dd',
    Float              = '#11eeee',
    Function           = '#40b0fd',
    FuncBuiltin        = '#40f0fd',
    FuncMacro          = '#40f0bd',
    Include            = { fg = '#bf68f9', bold = true },
    Keyword            = '#bf68d9',
    KeywordFunction    = '#bf68d9',
    KeywordOperator    = '#df69b4',
    KeywordReturn      = '#df68d9',
    Label              = '#ff6540',
    Method             = '#60b0fd',
    Namespace          = { fg = '#ff6540', bold = true },
    None               = '#9370db',
    Number             = '#11eeee',
    Operator           = '#ff69b4',
    Parameter          = '#40e0d0',
    ParameterReference = '#48d1cc',
    PreProc            = { fg = '#bf68f9', bold = true },
    Property           = '#4fa6dd',
    PunctDelimiter     = '#ffa07a',
    PunctBracket       = '#ffa07a',
    PunctSpecial       = '#ffa07a',
    Repeat             = '#bf68d9',
    StorageClass       = '#bf88d9',
    String             = '#8edd6b',
    StringRegex        = '#f0e68c',
    StringEscape       = '#3ea9e2',
    StringSpecial      = '#cd5c5c',
    Symbol             = '#ff6540',
    Tag                = { fg = '#fa6032', bold = true },
    TagAttribute       = { fg = '#fa8072', italic = true },
    TagDelimiter       = '#ffa07a',
    Text               = '#a0a8b7',
    -- Strong             = '',
    -- Emphasis           = '',
    -- Underline          = '',
    -- Strike             = '',
    -- Title              = '',
    -- Literal            = '',
    -- URI                = '',
    -- Math               = '',
    -- TextReference      = '',
    -- Enviroment         = '',
    -- EnvironmentName    = '',
    Note               = '#bf68d9',
    Warning            = '#e2b86b',
    Danger             = '#e55561',
    Todo               = '#48b0bd',
    Type               = '#fa8072',
    TypeBuiltin        = '#ba75d3',
    TypeQualifier      = '#ba55f3',
    TypeDefinition     = '#da55d3',
    Variable           = '#ffa500',
    VariableBuiltin    = '#df89d4',
}

M.rainbows = {
    '#dc143c',
    '#ff8c00',
    '#ffd700',
    '#32cd32',
    '#4169e1',
    '#a28be7',
    '#ba55d3',
}

return M
